# Namespace for services
servicesNamespace: oscar-svc
# Credentials for basic-auth
authUser: oscar
authPass: oscar123

# Enable a Serverless backend for sync invocations (""|openfaas)
serverlessBackend: ""

UsersAdmin: ""
TTLJob: 2592000
JobListingLimit: 70

# OpenFaaS configuration values
openfaas:
  namespace: openfaas
  port: 8080
  prometheusPort: 9090
  basicAuthSecret: basic-auth
  scaler:
    enable: false
    interval: "2m"
    inactivityDuration: "10m"
  watchdog:
    maxInflight: 1
    writeDebug: "true"
    execTimeout: 0
    readTimeout: 300
    writeTimeout: 300
    healthCheckInterval: 5

# Service configuration
service:
  type: NodePort
  port: 8080
  nodePort: 30301

# Additional OSCAR configuration
additionalConfig:
  allowedImagePrefix: []
  
# Number of replicas to deploy
replicas: 1

# Ingress configuration
ingress:
# Create a NGINX ingress to expose OSCAR
  create: false
  certManagerIssuer: ""
  host: ""

# Container image and pullPolicy for deployment
image:
  repository: ghcr.io/grycap/oscar
  tag: "3.7.1"
  pullPolicy: Always

# Read and write timeouts for OSCAR's HTTP server
readTimeout: 300
writeTimeout: 300

# MinIO credentials (must be deployed in the same cluster)
minIO:
  endpoint: https://minio-service.minio:9000
  TLSVerify: "true"
  region:  us-east-1
  accessKey: minio
  secretKey: minio123

# Apache YuniKorn configuration
yuniKorn:
  enable: false
  namespace: yunikorn
  configMap:  yunikorn-configs
  configFileName: queues.yaml

# ResourceManager configuration
resourceManager:
  enable: false
  interval: 15

# ReScheduler configuration
reScheduler:
  enable: false
  interval: 15
  threshold: 30

# OIDC configuration
oidc:
  enable: false
  issuer: "https://aai.egi.eu/auth/realms/egi"
  subject: ""
  groups: ""

# FaaS Supervisor and FWatchdog versions to populate the OSCAR's PV
volume:
  storageClassName: ""
  supervisorVersion: "1.6.2"
  watchdogVersion: "0.2.1"
  supervisorKit : "docker://ghcr.io/grycap/faas-supervisor-kit"
  enable: "true"
  default:
    available: "7Gi"
    max: "5"
    max_disk: "5Gi"
    min_disk: "200Mi"
# Liveness and Readiness probe values.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
tolerations: []
affinity: {}

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 512Mi
    cpu: 500m

# Configure kueue resource
kueue:
  enable: "false"
  default:
    cpu: "2"
    memory: "2Gi"
    flavor: "oscar-default-flavor"

# Configure Prometheus resource

prometheus:
  url: ""
  cpuQuery: "sum(increase(container_cpu_usage_seconds_total{namespace=~\"{{services_namespace}}.*\",service=~\"{{service}}\"}[{{range}}])) / 3600"
  gpuQuery: "sum(increase(container_gpu_usage_seconds_total{namespace=~\"{{services_namespace}}.*\",service=~\"{{service}}\"}[{{range}}])) / 3600"

# Configure Loki resource

loki:
  url: ""
  query: "{namespace=\"{{namespace}}\", app=\"{{app}}\"} |~ \"/(job|run)/\""
  exposedQuery: "{namespace=\"{{namespace}}\", app=\"{{app}}\"} |~ \"/system/services/.+/exposed\""
  exposedNamespace: "ingress-nginx"
  exposedAppLabel: "ingress-nginx"

# Configure Exposed Services

exposedServices:
  routeKind: "ingress"

# Configure HTTPRoute

httproute:
  create: false
  type: "traefik"
  host: ""
  gateway:
    name: "traefik-gateway"
    namespace: "traefik"

# Configure Ingress Services CORS

ingressServices:
  corsAllowedOrigins: "https://dashboard.oscar.grycap.net,https://dashboard-devel.oscar.grycap.net,https://dashboard-demo.oscar.grycap.net,http://oscar.oscar.svc.cluster.local,http://host.docker.internal,http://localhost,http://localhost:5173"
  corsAllowedMethods: "GET, PUT, POST, DELETE, PATCH, HEAD"
  corsAllowedHeaders: "Authorization, Content-Type"

# Additional config file path
additionalConfigPath: "config.yaml"