{{- if .Values.additionalConfig.allowedImagePrefix }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-oscar-config
  namespace: oscar-svc
data:
  config.yaml: |
    images:
      allowed_prefixes:
        {{- range .Values.additionalConfig.allowedImagePrefix }}
        - {{ . | quote}}
        {{- end }}
{{- end }}