---
{{- if .Values.createIngress }}
{{- if lt (int .Capabilities.KubeVersion.Minor) 19 }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: oscar
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - backend:
{{- if lt (int .Capabilities.KubeVersion.Minor) 19 }}
            serviceName: oscar
            servicePort: {{ .Values.service.port }}
{{- else }}
            service:
              name: oscar
              port:
                number: {{ .Values.service.port }}
          pathType: Prefix
{{- end }}
          path: /
{{- end }}