---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oscar-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oscar-controller
  namespace: {{ .Values.servicesNamespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - podtemplates
  - configmaps
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - deletecollection
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oscar-controller-binding
  namespace: {{ .Values.servicesNamespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oscar-controller
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.yuniKorn.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yunikorn-config-reader
  namespace: {{ .Values.yuniKorn.namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yunikorn-config-reader-binding
  namespace: {{ .Values.yuniKorn.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yunikorn-config-reader
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
{{- if .Values.resourceManager.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oscar-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oscar-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oscar-cluster-role
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oscar-controller-global
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - podtemplates
  - configmaps
  - secrets
  - services
  - persistentvolumeclaims
  - deletecollection
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - resourceflavors
  - clusterqueues
  - localqueues
  - workloads
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oscar-controller-global-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oscar-controller-global
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: {{ .Release.Namespace | quote }}
