apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oscar-pvc
  namespace: {{ .Values.servicesNamespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
{{- if ne .Values.volume.storageClassName "" }}
  storageClassName: {{ .Values.volume.storageClassName | quote }}
{{- end }}
  resources:
    requests:
      storage: 2Gi
