---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oscar-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oscar-controller
  namespace: {{ .Values.servicesNamespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - podtemplates
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
{{- if ne .Values.serverlessBackend "" }}
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
{{- end }}
{{- if eq (lower .Values.serverlessBackend) "openfaas" }}
- apiGroups:
  - openfaas.com
  resources:
  - functions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oscar-controller-binding
  namespace: {{ .Values.servicesNamespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oscar-controller
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: {{ .Release.Namespace | quote }}
{{- if and (eq (lower .Values.serverlessBackend) "openfaas") .Values.openfaas.scaler.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Values.openfaas.namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: {{ .Values.openfaas.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: {{ .Release.Namespace | quote }}
{{- end }}