apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oscar-pvc
  namespace: {{ .Values.servicesNamespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volume.storageClassName | quote }}
  resources:
    requests:
      storage: 2Gi
