apiVersion: v1
kind: Service
metadata:
  name: oscar
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: endpoint
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: oscar