{{- if semverCompare ">=3.4.0" .Values.image.tag }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ .Values.servicesNamespace }} 
stringData:
  oidc_uid: minio 
  accessKey: {{ .Values.minIO.accessKey | quote }} 
  secretKey: {{ .Values.minIO.secretKey | quote }} 
{{- end}}