apiVersion: v2
name: IM
description: Deploy a HA Infrastructure Manager
version: 1.5.1
type: application
home: https://www.grycap.upv.es/im
sources:
  - https://github.com/grycap/im
icon: https://github.com/grycap/helm-charts/raw/master/icons/im.png
keywords:
- Infrastructure Manager
- Cloud Orchestrator
- TOSCA
maintainers:
- email: micafer1@upv.es
  name: Miguel Caballer
dependencies:
  - name: mysql
    version: ">= 1.1.1"
    repository: https://charts.helm.sh/stable
  - name: vault
    version: ">= 0.17.1"
    repository: https://helm.releases.hashicorp.com
    condition: vault.enabled