mysql:
  mysqlUser: imuser
  mysqlPassword: impass
  mysqlRootPassword: imrootpass
  mysqlDatabase: imdb
  persistence:
    enabled: false
    storageClass: imdb
    accessMode: ReadWriteOnce
    size: 8Gi

haproxy:
  stats:
    ingress: false
    auth: "admin:admin"

imweb:
  version: 1.5.10-dev3

im:
  version: latest
  # In case of using more than 1 replica
  # the IM will be launched in HA mode
  replicas: 4
  log:
    level: DEBUG
    persistence:
      enabled: false
      storageclass: imlog
      accessmode: ReadWriteOnce
      size: 8Gi
  configmap:
    imcfg: |
      [im]
      # if you need to add more values check: https://raw.githubusercontent.com/grycap/im/master/etc/im.cfg
      ACTIVATE_XMLRPC = False
      ACTIVATE_REST = True
      INF_CACHE_TIME = 3600
      PLAYBOOK_RETRIES = 3