mysql:
  mysqlUser: imuser
  mysqlPassword: impass
  persistence:
    enabled: false
    storageClass: imdb
    accessMode: ReadWriteOnce
    size: 8Gi
  initializationFiles:
    imweb.sql: |-
      CREATE DATABASE IF NOT EXISTS imweb;
    imdb.sql: |-
      CREATE DATABASE IF NOT EXISTS imdb;

imweb:
  version: latest

im:
  version: latest
  # In case of using more than 1 replica
  # the IM will be launched in HA mode
  replicas: 1
  log:
    level: DEBUG
    persistence:
      enabled: false
      storageclass: imlog
      accessmode: ReadWriteOnce
      size: 8Gi
  # if you need to add values check: https://raw.githubusercontent.com/grycap/im/master/etc/im.cfg
  config: []