---
apiVersion: v1
kind: ConfigMap
metadata:
  name: im
data:
  logging.conf: |
      [loggers]
      keys=root,ConfManager,CloudConnector,InfrastructureManager
      [handlers]
      keys=fileHandler
      [formatters]
      keys=simpleFormatter
      [logger_root]
      level=ERROR
      handlers=fileHandler
      [logger_ConfManager]
      level=DEBUG
      handlers=fileHandler
      qualname=ConfManager
      propagate=0
      [logger_CloudConnector]
      level=DEBUG
      handlers=fileHandler
      qualname=CloudConnector
      propagate=0
      [logger_InfrastructureManager]
      level=DEBUG
      handlers=fileHandler
      qualname=InfrastructureManager
      propagate=0
      [handler_fileHandler]
      level={{ .Values.im.log.level }}
      formatter=simpleFormatter
{{- if eq .Values.im.replicas 1.0 }}
      class=logging.handlers.RotatingFileHandler
      args=('/var/log/im/im.log', 'w', 10485760, 3)
      [formatter_simpleFormatter]
      format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
{{- else }}
      class=logging.handlers.SysLogHandler
      args=(('im-log', 514),)
      [formatter_simpleFormatter]
      format=%(asctime)s - %(hostname)s - %(name)s - %(levelname)s - %(message)s
{{- end }}
      datefmt=
  im.cfg: |
{{ .Values.im.configmap.imcfg | indent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-backend
  labels:
    name: im-backend
spec:
  replicas: {{ .Values.im.replicas }}
  selector:
    matchLabels:
      name: im-backend
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: im-backend
    spec:
      containers:
      - name: im
        image: grycap/im:{{ .Values.im.version }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8800
        imagePullPolicy: Always
        env:
          - name: IM_DATA_DB
            value: mysql://{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@{{ .Release.Name }}-mysql/{{ .Values.mysql.mysqlDatabase }}
        volumeMounts:
           - name: im
             mountPath: /etc/im/logging.conf
             subPath: logging.conf
           - name: im
             mountPath: /etc/im/im.cfg
             subPath: im.cfg
{{- if eq .Values.im.replicas 1.0 }}
           - name: imlog
             mountPath: /var/log/im
{{- end }}
        livenessProbe:
          httpGet:
            path: /version
            port: 8800
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
      volumes:
        - name: im
          configMap:
            name: im
{{- if eq .Values.im.replicas 1.0 }}
        - name: imlog
{{- if .Values.im.log.persistence.enabled }}
          persistentVolumeClaim:
            claimName: imlog
{{- else }}
          emptyDir: {}
{{ end }}
{{ end }} 

---
apiVersion: v1
kind: Service
metadata:
  name: im-backend
spec:
  ports:
  - name: restapi
    port: 8800
  selector:
    name: im-backend
