---
apiVersion: v1
kind: ConfigMap
metadata:
  name: im
data:
  im.cfg: |
{{ .Values.im.configmap.imcfg | indent 4 }}
  logging.conf: |
{{ .Values.im.configmap.loggingconf | indent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-backend
  labels:
    name: im-backend
spec:
  replicas: {{ .Values.im.replicas }}
  selector:
    matchLabels:
      name: im-backend
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: im-backend
    spec:
      containers:
      - name: im
        image: grycap/im:{{ .Values.im.version }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8800
        imagePullPolicy: Always
        env:
          - name: IM_DATA_DB
            value: mysql://{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@{{ .Release.Name }}-mysql/{{ .Values.mysql.mysqlDatabase }}
        volumeMounts:
           - name: im
             mountPath: /etc/im/logging.conf
             subPath: logging.conf
           - name: im
             mountPath: /etc/im/im.cfg
             subPath: im.cfg
        livenessProbe:
          httpGet:
            path: /version
            port: 8800
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
      volumes:
        - name: im
          configMap:
            name: im

---
apiVersion: v1
kind: Service
metadata:
  name: im-backend
spec:
  ports:
  - name: restapi
    port: 8800
  selector:
    name: im-backend

