---
apiVersion: v1
kind: ConfigMap
metadata:
  name: im
data:
  logging.conf: |
      [loggers]
      keys=root,ConfManager,CloudConnector,InfrastructureManager
      [handlers]
      keys=fileHandler
      [formatters]
      keys=simpleFormatter
      [logger_root]
      level=ERROR
      handlers=fileHandler
      [logger_ConfManager]
      level=DEBUG
      handlers=fileHandler
      qualname=ConfManager
      propagate=0
      [logger_CloudConnector]
      level=DEBUG
      handlers=fileHandler
      qualname=CloudConnector
      propagate=0
      [logger_InfrastructureManager]
      level=DEBUG
      handlers=fileHandler
      qualname=InfrastructureManager
      propagate=0
      [handler_fileHandler]
      level={{ .Values.im.log.level }}
      formatter=simpleFormatter
{{- if eq .Values.im.replicas 1.0 }}
      class=logging.handlers.RotatingFileHandler
      args=('/var/log/im/im.log', 'w', 10485760, 3)
      [formatter_simpleFormatter]
      format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
{{- else }}
      class=logging.handlers.SysLogHandler
      args=(('im-log', 514),)
      [formatter_simpleFormatter]
      format=%(asctime)s - %(hostname)s - %(name)s - %(levelname)s - %(message)s
{{- end }}
      datefmt=
  im.cfg: |
    [im]
    ACTIVATE_XMLRPC = False
    ACTIVATE_REST = True
{{- if gt .Values.im.replicas 1.0 }}
    INF_CACHE_TIME = 3600
{{- end }}
{{- if .Values.vault.enabled }}
    VAULT_URL = https://RELEASE-NAME-vault:8200
{{- end }}
    {{- range .Values.im.config }}
    {{ . | }}
    {{- end }}
