---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-backend
  labels:
    name: im-backend
spec:
  replicas: {{ .Values.im.replicas }}
  selector:
    matchLabels:
      name: im-backend
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: im-backend
    spec:
      containers:
      - name: im
        image: {{ .Values.im.image }}:{{ .Values.im.version }}
        resources:
          requests:
            memory: "{{ .Values.im.resources.requests.memory }}"
            cpu: "{{ .Values.im.resources.requests.cpu }}"
        ports:
        - containerPort: 8800
        imagePullPolicy: Always
        env:
          - name: IM_DATA_DB
{{- if .Values.mongodb.enabled }}
            value: mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@
{{- range (untilStep 0 (int .Values.mongodb.replicaCount) 1) -}}
{{- if ne . 0 }},{{ end -}}
mongodb-{{ . }}.mongodb-headless
{{- end -}}
/{{ .Values.mongodb.auth.database }}
{{- else }}
            value: mysql://{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@{{ .Release.Name }}-mysql/imdb
{{- end }}
        volumeMounts:
           - name: im
             mountPath: /etc/im/logging.conf
             subPath: logging.conf
           - name: im
             mountPath: /etc/im/im.cfg
             subPath: im.cfg
{{- if eq .Values.im.replicas 1.0 }}
           - name: imlog
             mountPath: /var/log/im
{{- end }}
        livenessProbe:
          httpGet:
            path: /version
            port: 8800
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
      volumes:
        - name: im
          configMap:
            name: im
{{- if eq .Values.im.replicas 1.0 }}
        - name: imlog
{{- if .Values.im.log.persistence.enabled }}
          persistentVolumeClaim:
            claimName: imlog
{{- else }}
          emptyDir: {}
{{ end }}
{{ end }} 
