{{ if gt .Values.im.replicas 1.0 }}
# Deployment for the Syslog service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-log
  labels:
    name: im-log
spec:
  replicas: 1
  selector:
    matchLabels:
      name: im-log
  template:
    metadata:
      labels:
        name: im-log
    spec:
      containers:
        - name: im-log
          image: voxxit/rsyslog
          ports:
          - containerPort: 514
            protocol: TCP
            name: syslogtcp
          - containerPort: 514
            protocol: UDP
            name: syslog
          volumeMounts:
           - name: imlog
             mountPath: /var/log
          livenessProbe:
            tcpSocket:
              port: 514
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
      volumes:
        - name: imlog
{{- if .Values.im.log.persistence.enabled }}
          persistentVolumeClaim:
            claimName: imlog
{{- else }}
          emptyDir: {}
{{ end }}

{{ end }}