{{ if gt .Values.im.replicas 1.0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: im-load-balancer-svc
spec:
  ports:
  - name: http
    port: 80
  - name: stats
    port: 1936
  selector:
    run: haproxy-load-balancer
{{ end }}