---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-root-password
type: Opaque
stringData:
  password: {{ .Values.mongodb.auth.rootPassword }}
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: im-mongodb
spec:
  members: {{ .Values.mongodb.replicaCount }}
{{ if  .Values.mongodb.arbiter.enabled }}
  arbiters: 1
{{ end }}
  type: ReplicaSet
  version: "{{ .Values.mongodb.version }}"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodb.auth.rootUser }}
      db: admin
      passwordSecretRef:
        name: mongodb-root-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWrite
          db: imdb
      scramCredentialsSecretName: im-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
{{ .Values.mongodb.resources | toYaml | indent 16 }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [{{ .Values.mongodb.data.persistence.accessMode }}]
            resources:
              requests:
                storage: {{ .Values.mongodb.data.persistence.size }}
        - metadata:
            name: logs-volume
          spec:
            accessModes: [{{ .Values.mongodb.log.persistence.accessMode }}]
            resources:
              requests:
                storage: {{ .Values.mongodb.log.persistence.size }}
