# Deployment for the IM-web service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: im-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: im-web
  template:
    metadata:
      labels:
        name: im-web
    spec:
      containers:
        - name: im-web
          image: grycap/im-web:{{ .Values.imweb.version }}
          resources:
            requests:
              memory: "{{ .Values.imweb.resources.requests.memory }}"
              cpu: "{{ .Values.imweb.resources.requests.cpu }}"
          ports:
          - containerPort: 80
            protocol: TCP
            name: http
          env:
          - name: im_use_rest
            value: "true"
          - name: im_host
{{- if eq .Values.im.replicas 1.0 }}
            value: im-backend
{{- else }}
            value: im-load-balancer-svc
{{- end }}
          - name: im_port
{{- if eq .Values.im.replicas 1.0 }}
            value: "8800"
{{- else }}
            value: "80"
{{- end }}
          - name: im_db
            value: mysql://{{ .Values.mysql.mysqlUser }}:{{ .Values.mysql.mysqlPassword }}@{{ .Release.Name }}-mysql/imweb
          volumeMounts:
           - name: im-web
             mountPath: /var/www/html/im-web/analyticstracking.php
             subPath: analyticstracking.php
          livenessProbe:
            httpGet:
              path: /im-web/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
      volumes:
        - name: im-web
          configMap:
            name: im-web