---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: im-web
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /im-web
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: im-web-svc
            servicePort: 80
          path: /im-web/?(.*)

