{{ if  .Values.imweb.deploy }}
# In case you want to track web usage using Google Analytics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: im-web
data:
  analyticstracking.php: |
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script>
    </script>
{{ end }}