{{ if and .Values.imweb.deploy .Values.imweb.ingress.enabled }}
---
{{- if lt (int .Capabilities.KubeVersion.Minor) 19 }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: im-web
  annotations:
      nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
      nginx.ingress.kubernetes.io/proxy-body-size: 20m
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
      nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ .Values.imweb.ingress.path }}
spec:
  ingressClassName: nginx
  rules:
{{- if .Values.imweb.ingress.host }}
    - host: {{ .Values.imweb.ingress.host }}
      http:
{{- else }}
    - http:
{{- end }}
        paths:
        - backend:
{{- if lt (int .Capabilities.KubeVersion.Minor) 19 }}
            serviceName: im-web-svc
            servicePort: 80
{{- else }}
            service:
              name: im-web-svc
              port:
                number: 80
          pathType: Prefix
{{- end }}
          path: {{ .Values.imweb.ingress.path }}/?(.*)
{{- if .Values.imweb.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.imweb.ingress.tls | indent 4) . }}
{{- end -}}
{{ end }}
