# Volume Claims
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: imlog
spec:
  storageClassName: {{ .Values.pvcs.imlog.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcs.imlog.size }}